### ISSUE TITLE
Support *:terms to search all fields in the index

### ISSUE THREAD

**Issue by payammeyer** [zuliaio/zuliasearch#2]
The user may want to query all fields and they shouldn't have to name every field specifically, ensure (*:term1 term2 term3) actually searches all fields for the given terms.

**Comment by mdavis95** [comment]
probably would be nice to support any wildcard so prefix*:term would work

**Comment by mdavis95** [comment]
this works in qf as well as queries.

the follow are supported:
*fieldSuffix:someTerm
fieldPrefix*:someTerm
*:someTerm
