### ISSUE TITLE
Change Associated Meta To Accept Any JSON/BSON metadata

### ISSUE THREAD

**Issue by payammeyer** [zuliaio/zuliasearch#8]
The current structure for meta is Map<String, String>. This was done due to a protobuf limitation of key/value only and no handling for generic objects. This needs to be changed to accept a byte[] so that a bson document with proper types can be stored.

**Comment by mdavis95** [comment]
the protobuf will take a byte array
the java client will take a MongoDB document object and encode as byte array
the rest client will take a Json

**Comment by mdavis95** [comment]
Fixed in version 1.2
